name: 'core_telecoms'
version: '1.0.0'
config-version: 2

profile: 'core_telecoms'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  core_telecoms:
    # Silver Layer (Views)
    staging:
      +materialized: view
      +schema: STAGING
    # Gold Layer (Tables)
    marts:
      +materialized: table
      +schema: ANALYTICS